docker pull istio/proxyv2:1.14.1
docker pull istio/pilot:1.14.1
docker pull redis:6.2.6-alpine
docker pull ghcr.io/dexidp/dex:v2.30.2
docker pull k8s.gcr.io/kube-apiserver:v1.21.4
docker pull k8s.gcr.io/kube-controller-manager:v1.21.4
docker pull k8s.gcr.io/kube-scheduler:v1.21.4
docker pull k8s.gcr.io/kube-proxy:v1.21.4
docker pull gcr.io/k8s-minikube/storage-provisioner:v5
docker pull k8s.gcr.io/pause:3.4.1
docker pull registry
docker pull k8s.gcr.io/coredns/coredns:v1.8.0
docker pull k8s.gcr.io/etcd:3.4.13-0
docker pull gcr.io/google_containers/kube-registry-proxy
docker pull quay.io/argoproj/argocd:v2.2.5
docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook
docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller
docker pull gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard
