apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cs-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cs-role
subjects:
  - namespace: default
    kind: ServiceAccount
    name: cs-user
